use_frameworks!

platform :ios, '9.0'

target 'XJScrollViewStateManager_Example' do
  pod 'XJScrollViewStateManager', :path => '../'

  target 'XJScrollViewStateManager_Tests' do
    inherit! :search_paths

    
  end
end
